[workspace]

members = [
    "Ch.1 First Web Scraper",
    "Ch.2 Advanced HTML Parsing",
    "Ch.3 Writing Web Crawlers",
    "Ch.4 Web Crawling Models",
    "Ch.5 Storing Data",
    "Ch.6 Reading Documents",
    "Ch.7 Cleaning Data",
]
resolver = "2"
